---
name: Update Terraform Lock File
description: Update terraform lock file to include hashes for both platforms

inputs:
  app-id:
    description: Application ID
    required: true

  app-pem:
    description: Application private key
    required: true

runs:
  using: composite
  steps:
    - name: Generate token
      id: generate-token
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      with:
        client-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.app-pem }}

    - name: Checkout source
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: true
        ref: ${{ github.head_ref || github.ref_name }}
        repository: ${{ github.repository }}
        token: ${{ steps.generate-token.outputs.token }}

    - name: Setup terraform
      uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

    - name: Update lock file for all platforms
      shell: bash
      run: |-
        find . -name ".terraform.lock.hcl" -print0 | while IFS= read -r -d '' lockfile; do
          dir=$(dirname "$lockfile")
          echo "Initialising $dir"
          terraform -chdir="$dir" init -backend=false -upgrade
          echo "Locking providers in $dir"
          terraform -chdir="$dir" providers lock \
            -platform=darwin_amd64 \
            -platform=linux_amd64
        done

    - name: Commit updated lock files
      uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
      with:
        commit_message: update terraform lock file for both platforms
        file_pattern: "**/.terraform.lock.hcl"
