---
repos:
  - repo: local
    hooks:
      - id: terraform-stacks-validate
        name: Terraform stacks validate
        description: Validates all Terraform stacks configuration files
        entry: ../hooks/terraform-stacks-validate.sh
        files: \.hcl$
        language: script
        exclude: \.terraform\/.*$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          - >-
            --config-data={
              extends: default,
              rules: {
                anchors: enable,
                braces: {
                  forbid: non-empty
                },
                brackets: {
                  forbid: non-empty
                },
                colons: enable,
                commas: enable,
                comments: {
                  min-spaces-from-content: 1
                },
                comments-indentation: enable,
                document-end: disable,
                document-start: enable,
                empty-lines: enable,
                empty-values: disable,
                float-values: enable,
                hyphens: enable,
                indentation: enable,
                key-duplicates: enable,
                key-ordering: disable,
                line-length: {
                  max: 160
                },
                new-line-at-end-of-file: enable,
                new-lines: enable,
                octal-values: enable,
                quoted-strings: {
                  quote-type: double,
                  required: only-when-needed
                },
                trailing-spaces: enable,
                truthy: {
                  check-keys: false
                }
              }
            }
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.101.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-diff
      - id: terraform_validate
        args:
          - --tf-init-args=-upgrade
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.14.0
    hooks:
      - id: hadolint
        args:
          - --ignore=DL3008
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v26.4.0
    hooks:
      - id: ansible-lint
        args:
          - --exclude=.github
          - --exclude=docker-compose.yml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        args:
          - --exit-non-zero-on-fix
          - --fix
      - id: ruff-format
  - repo: https://github.com/crate-ci/typos
    rev: v1.37.1
    hooks:
      - id: typos
        args:
          - --force-exclude
          - --hidden
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args:
          - --disable=MD013
          - --disable=MD031
          - --disable=MD033
          - --dot
          - --fix
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-tabs
        exclude: \.tsv$
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.3
    hooks:
      - id: toml-sort-fix
        args:
          - --all
          - --in-place
          - --spaces-indent-inline-array=4
          - --trailing-comma-inline-array
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.6.2
    hooks:
      - id: prettier
        args:
          - --prose-wrap=always
          - --quote-props=as-needed
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args:
          - --enforce-all
          - --maxkb=2000
      - id: check-case-conflict
      - id: check-executables-have-shebangs
        exclude: ^.terraform.lock.hcl$
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args:
          - --external-sources
          - --shell=bash
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.10
    hooks:
      - id: actionlint
