---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: ./actions/linting
        with:
          pre-commit-config: ./.pre-commit-config.yaml
