---
name: Lint

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
